name: Feature Request
description: Suggest a new feature or improvement
title: "feat: "
labels: ["enhancement"]
projects: ["xberg-io/1"]
body:
  - type: textarea
    id: what
    attributes:
      label: What is the proposed feature?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would this be a good addition?
    validations:
      required: true
